service:
  type: NodePort
  ports:
  - name: status-port
    nodePort: 32701
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http
    nodePort: 32702
    port: 8080
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 32703
    port: 8443
    protocol: TCP
    targetPort: 443