apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: localstack

helmGlobals:
 chartHome: ../../../../../charts

helmCharts:
# https://artifacthub.io/packages/helm/argo/argo-cd
- name: localstack
  repo: https://localstack.github.io/helm-charts
  version: 0.6.27
  valuesFile: values.yaml
  releaseName: localstack
  includeCRDs: true