apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: rabbitmq
    argocd.argoproj.io/instance: in-cluster-albion-killbot-rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rabbitmq
        app.kubernetes.io/instance: rabbitmq
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: rabbitmq
    spec:
      volumes:
        - name: rabbitmq-data
          emptyDir: {}
        - name: rabbitmq-config
          emptyDir: {}
      containers:
        - name: rabbitmq
          ports:
            - name: rabbitmq
              containerPort: 15672
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /data/db
            - name: rabbitmq-config
              mountPath: /data/configdb
          image: rabbitmq:3-management