apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - clusters: {}
      - git:
          repoURL: &repo https://github.com/ymedlop/argocd-clusters-management.git
          revision: &branch main
          directories:
          - path: clusters/groups/on-prem/{{name}}/overlays/*/rendered
          - path: clusters/groups/on-prem/in-cluster/overlays/argocd
            exclude: true
  template:
    metadata:
      name: '{{name}}-{{path[5]}}'
    spec:
      project: addons
      source:
        repoURL: *repo
        targetRevision: *branch
        path: '{{path}}'
      destination:
        name: '{{name}}'
        namespace: '{{path[5]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
      - group: admissionregistration.k8s.io/v1
        kind: ValidatingWebhookConfiguration
        name: istiod-default-validator
        namespace: istio-system
        jsonPointers:
        - /webhooks[0]/failurePolicy