apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

helmGlobals:
 chartHome: ../../../../../charts

helmCharts:
  # https://artifacthub.io/packages/helm/cert-manager/cert-manager
- name: cert-manager
  namespace: cert-manager
  repo: https://charts.jetstack.io/
  version: 1.13.3
  valuesFile: ../../../../../base/cert-manager/values.yaml
  releaseName: cert-manager

resources:
- ../../../../../base/cert-manager