apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - clusters: {}
      - git:
          repoURL: &repo https://github.com/ymedlop/argocd-clusters-management.git
          revision: &branch main
          directories:
          - path: clusters/groups/on-prem/dev/{{name}}/overlays/*
          - path: clusters/groups/on-prem/dev/in-cluster/overlays/argocd
            exclude: true
  template:
    metadata:
      name: '{{name}}-{{path.basename}}'
    spec:
      project: addons
      source:
        repoURL: *repo
        targetRevision: *branch
        path: '{{path}}'
      destination:
        name: '{{name}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true