apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-argocd-config
  namespace: argocd
spec:
  project: addons
  source:
    repoURL: https://github.com/ymedlop/argocd-clusters-management.git
    targetRevision: HEAD
    path: clusters/groups/on-prem/dev/in-cluster/overlays/argocd/config
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true